CREATE TABLE task_sections (
    id BIGINT NOT NULL,
    CONSTRAINT pk_task_sections PRIMARY KEY (id),
    CONSTRAINT fk_task_sections_on_id FOREIGN KEY (id) REFERENCES event_sections (id)
);

CREATE TABLE tasks (
    id BIGINT NOT NULL,
    default_language VARCHAR(32) NOT NULL,
    cpu_time_limit_ms INTEGER NOT NULL,
    wall_time_limit_ms INTEGER NOT NULL,
    memory_limit_mb INTEGER NOT NULL,
    grading_strategy VARCHAR(16) NOT NULL,
    output_match VARCHAR(32) NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id),
    CONSTRAINT fk_tasks_on_id FOREIGN KEY (id) REFERENCES gradable_events (id)
);

CREATE TABLE task_allowed_languages (
    task_id BIGINT NOT NULL,
    language VARCHAR(32) NOT NULL,
    CONSTRAINT pk_task_allowed_languages PRIMARY KEY (task_id, language),
    CONSTRAINT fk_task_allowed_languages_on_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE
);

CREATE TABLE task_starter_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    task_id BIGINT NOT NULL,
    language VARCHAR(32) NOT NULL,
    starter_code TEXT,
    CONSTRAINT pk_task_starter_codes PRIMARY KEY (id),
    CONSTRAINT fk_task_starter_codes_on_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT uq_starter_code_task_language UNIQUE (task_id, language)
);

CREATE TABLE task_test_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    task_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL,
    name VARCHAR(128),
    input TEXT,
    expected_output TEXT,
    is_visible BOOLEAN NOT NULL DEFAULT FALSE,
    weight NUMERIC(5, 2) NOT NULL DEFAULT 1.00,
    time_limit_override_ms INTEGER,
    CONSTRAINT pk_task_test_cases PRIMARY KEY (id),
    CONSTRAINT fk_task_test_cases_on_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT uq_test_case_task_order_index UNIQUE (task_id, order_index)
);

CREATE TABLE task_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    task_id BIGINT NOT NULL,
    animal_id BIGINT NOT NULL,
    language VARCHAR(32) NOT NULL,
    source_code TEXT NOT NULL,
    status VARCHAR(16) NOT NULL,
    score NUMERIC(4, 1),
    passed_weight NUMERIC(7, 2),
    total_weight NUMERIC(7, 2),
    passed_count INTEGER,
    total_count INTEGER,
    error_message TEXT,
    attempt INTEGER NOT NULL DEFAULT 0,
    created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_date TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    CONSTRAINT pk_task_submissions PRIMARY KEY (id),
    CONSTRAINT fk_task_submissions_on_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_submissions_on_animal FOREIGN KEY (animal_id) REFERENCES animals (id)
);

CREATE TABLE task_submission_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    submission_id BIGINT NOT NULL,
    test_case_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    actual_output TEXT,
    stdout TEXT,
    stderr TEXT,
    exit_code INTEGER,
    execution_time_ms INTEGER,
    CONSTRAINT pk_task_submission_results PRIMARY KEY (id),
    CONSTRAINT fk_submission_results_on_submission FOREIGN KEY (submission_id) REFERENCES task_submissions (id) ON DELETE CASCADE,
    CONSTRAINT fk_submission_results_on_test_case FOREIGN KEY (test_case_id) REFERENCES task_test_cases (id),
    CONSTRAINT uq_submission_result_submission_test_case UNIQUE (submission_id, test_case_id)
);