name: Run Tests

on: 
  workflow_call:
    inputs:
      working-directory: 
        type: string
        description: 'Working backend directory'
        required: false
        default: './polymorphia-backend'
      spring-profile:
        type: string
        description: 'Spring profile to use'
        required: false
        default: 'test'
    outputs:
      test-result:
        description: 'Test execution result'
        value: ${{ jobs.test-backend.outputs.result }}
  workflow_dispatch:
    inputs:
      working-directory: 
        type: string
        description: 'Working backend directory'
        required: false
        default: './polymorphia-backend'
      spring-profile:
        type: string
        description: 'Spring profile to use'
        required: false
        default: 'test'

jobs: 
  test-backend: 
    runs-on: ubuntu-latest

    permissions:
        contents: read
        checks: write  
        pull-requests: write

    outputs:
      result: ${{ steps.test-backend.outcome }}
    
    steps: 
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Java with Maven
        uses: ./.github/actions/ci_setup_java
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Run Tests
        id: test-backend
        working-directory: ${{ inputs.working-directory }}
        run: |
          mvn clean test -Dspring.profiles.active=${{ inputs.spring-profile }} -B -V
  
      - name: Build Test Container
        working-directory: ./polymorphia-backend
        run: |
          docker build -t polymorphia-backend:test-container -f Dockerfile .

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Backend Tests
          path: ${{ inputs.working-directory }}/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
          list-tests: failed     
          max-annotations: 10
