name: Build and Deploy Backend to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  statuses: write
  contents: read
  checks: write
  id-token: write

concurrency:
  group: deploy-staging
  cancel-in-progress: false

jobs:
  run-tests:
    name: Run Tests
    uses: ./.github/workflows/run_tests.yml

  migrate:
    name: Run Migrations
    needs: [run-tests]
    uses: ./.github/workflows/run_migrations.yml
    secrets:
      DB_HOST: ${{ secrets.STAGING_DB_HOST }}
      DB_PORT: ${{ secrets.STAGING_DB_PORT }}
      DB_NAME: ${{ secrets.STAGING_DB_NAME }}
      DB_USER: ${{ secrets.STAGING_DB_USER }}
      DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}

  build-push:
    name: Build and Push
    needs: [migrate]
    uses: ./.github/workflows/build_push.yml
    with:
      environment: staging
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      ARTIFACT_REGISTRY_NAME: ${{ secrets.ARTIFACT_REGISTRY_NAME }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

  deploy:
    name: Deploy
    needs: [build-push]
    uses: ./.github/workflows/deploy_to_env.yml
    with:
      environment: staging
      container-port: 8081
      health-check-delay: 500
    secrets:
      VM_IP: ${{ secrets.STAGING_VM_IP }}
      VM_USER: ${{ secrets.STAGING_VM_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      ARTIFACT_REGISTRY_NAME: ${{ secrets.ARTIFACT_REGISTRY_NAME }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      HEALTH_ENDPOINT: ${{ secrets.HEALTH_ENDPOINT }}
      APP_DOMAIN: ${{ secrets.STAGING_APP_DOMAIN }}