name: "Deploy | Executor to Production"

on:
  push:
    branches:
      - main
    paths:
      - "polymorphia-code-executor/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-executor-prod
  cancel-in-progress: false

jobs:
  deploy:
    if: github.event_name != 'workflow_dispatch' || github.actor == 'krudny'
    name: Deploy Executor to Production
    uses: ./.github/workflows/deploy_executor_to_env.yml
    with:
      environment: production
      service-name: polymorphia-code-executor
      service-port: 8100
      target-dir: /mnt/data/executor
    secrets:
      VM_IP: ${{ secrets.PRODUCTION_VM_IP }}
      VM_USER: ${{ secrets.PRODUCTION_VM_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
