name: Build and Deploy Backend to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  statuses: write
  contents: read
  checks: write
  id-token: write

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  run-tests:
    name: Run Tests
    uses: ./.github/workflows/run_tests.yml

  migrate:
    name: Run Migrations
    needs: [run-tests]
    uses: ./.github/workflows/run_migrations.yml
    secrets:
      DB_HOST: ${{ secrets.PRODUCTION_DB_HOST }}
      DB_PORT: ${{ secrets.PRODUCTION_DB_PORT }}
      DB_NAME: ${{ secrets.PRODUCTION_DB_NAME }}
      DB_USER: ${{ secrets.PRODUCTION_DB_USER }}
      DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}

  build-push:
    name: Build and Push
    needs: [migrate]
    uses: ./.github/workflows/build_push.yml
    with:
      environment: production
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      ARTIFACT_REGISTRY_NAME: ${{ secrets.ARTIFACT_REGISTRY_NAME }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

  deploy:
    name: Deploy
    needs: [build-push]
    uses: ./.github/workflows/deploy_to_env.yml
    with:
      environment: production
      container-port: 8080
      health-check-delay: 600
    secrets:
      VM_IP: ${{ secrets.PRODUCTION_VM_IP }}
      VM_USER: ${{ secrets.PRODUCTION_VM_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      ARTIFACT_REGISTRY_NAME: ${{ secrets.ARTIFACT_REGISTRY_NAME }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      HEALTH_ENDPOINT: ${{ secrets.HEALTH_ENDPOINT }}
      APP_DOMAIN: ${{ secrets.PRODUCTION_APP_DOMAIN }}